# Generated by Django 5.2.1 on 2025-06-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
